import os

env = Environment(CXXFLAGS='-std=c++14 -O2')

if 'BOOST_PATH' in os.environ:
  boost_path = os.environ.get('BOOST_PATH')
  env.Append(CPPPATH=[os.path.join(boost_path, 'include')])
  env.Append(LIBPATH=[os.path.join(boost_path, 'lib')])

if not env.GetOption('clean'):
  conf = Configure(env)
  if not conf.CheckLibWithHeader(
      'boost_system', 'boost/asio.hpp', 'cxx'):
    print 'Could not find boost::asio'
    Exit(1)
  if not conf.CheckLibWithHeader(
      'boost_date_time', 'boost/date_time.hpp', 'cxx'):
    print 'Could not find boost::asio'
    Exit(1)
  env = conf.Finish()

SConscript('src/SConscript', 'env', variant_dir='build', duplicate=0)

